version: '3'
services:
  bookvalleswp-db:
    container_name: bookvalleswp-db
    image: mariadb:10
    restart: unless-stopped
    env_file: .env_db
    ports: [3260:3260]
    volumes: ['/var/lib/mysql/bookvalleswp:/var/lib/mysql']

  bookvalleswp:
    container_name: bookvalleswp
    image: wordpress:5
    restart: unless-stopped
    env_file: .env_wp
    ports: [81:80]
    volumes: []
    depends_on: ['bookvalleswp-db']
